### ISSUE TITLE
Try to run Procesamiento.m but missing some functions

### ISSUE THREAD

**Issue by zzwei1** [collado1992/Weather-Radar-Simulator#1]
Dear  collado1992,

I'm new at weather radar and radar meteorology, and I'm doing some research about simulating weather radar I/Q series and products. I found your  Weather-Radar-Simulator a helpful tool for me to study!
While when try to run Procesamiento.m, I found I don't have the 'PPPuniforme' function, 'ppi_plot' function and maybe other functions. Could you please update these functions in your ' Weather-Radar-Simulator' on github if possible? And when you have time, could I ask you some questions about weather radar simulator?

Thank you in advance for your help!

Yours sincerely,

zzwei

**Comment by collado1992** [comment]
Hello zzwei, yes, these files are missing from this repo (intentionaly). The script Procesamiento.m is for testing the simulator. this script contain the path to the processors (Pulse Pair Processing (PPP) and Gaussian Model Adaptive Processing GMAP). Try to implement these algorithm for yourself, if not I will update the repo in a few days and I will add the missing files. You can ask whatever about weather radar. I am working with weather signal processing, specially clutter filter and spectral moment estimation  for uniform and staggered scheme. 

regards
Arturo Collado Rosell

**Comment by zzwei1** [comment]
Thank you for your reply! 

I've heard about the PPP algorithm before, and I'll try to implement the PPP and GMAP algorithms by my self first, and may be you could update the repo a few days later so that I could check if my results are correct.

By the way, does the staggered and uniform scheme mean alternate transmission and simultaneous reception (ATSR) and simultaneous transmission and reception of horizontal and vertical
polarizations (SHV) methods of a polarimetric weather radar ?

Could this Weather-Radar-Simulator simulate the I/Q series of a specific meteorological scene such as rain or a storm? I found that weather radar simulators could be classified by whether they produce time series data ordirectly simulate products such as Doppler moments and polarimetric variables from the following paper: https://ieeexplore.ieee.org/document/7448402, and I have tried to generate a simulator which could directly simulate polarimetric variables(such as Zh, Zv, Zdr, Kdp). WRF(The Weather Research and Forecasting Model) is used to generate a 'realistic' meteorological scene and the WRF outputs are used to estimate the drop size distribution (DSD), the T-Matrix method is used to calculate the electromagnetic scattering. But I can't generate the I/Q series from my method now, I don't konw how to use my current results(such as Zh, Zv, Zdr, Kdp in a shape of 3-D matrix containing latitudes, longitudes and heights) to generate the I/Q series.Could you give me some advice? 

Yours sincerely,

zzwei

**Comment by collado1992** [comment]
Uniform means the radar use a unique Pulse Repetition Time (PRT), and staggered means that the radar uses more than one PRTs, the most common case is when the radar use alternately PRT1, PRT2, PRT1, PRT2, .......
My radar simulator does not have polarimetric information yet. This simulator, only give you the IQ time series data. I made it for generate "clouds", ground clutter and apply the algorithms to filter and recover the phenomenon spectral moments.
If you want to write my, this is my email: arturo.collado@ib.edu.ar
